# Generated by Django 3.1.3 on 2021-04-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='f_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='account',
            name='l_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
